package ch.kbw.portalumni.hibernatedata;
// Generated Apr 29, 2018 1:00:13 PM by Hibernate Tools 4.3.1



/**
 * Benutzer generated by hbm2java
 */
public class Benutzer  implements java.io.Serializable {


     private Integer idBenutzer;
     private Firma firma;
     private String nachname;
     private String vorname;
     private String email;
     private String passwort;
     private boolean admin;
     private boolean newsletter;
     private boolean enabled;

    public Benutzer() {
    }

	
    public Benutzer(String nachname, String vorname, String email, String passwort, boolean admin, boolean newsletter, boolean enabled) {
        this.nachname = nachname;
        this.vorname = vorname;
        this.email = email;
        this.passwort = passwort;
        this.admin = admin;
        this.newsletter = newsletter;
        this.enabled = enabled;
    }
    public Benutzer(Firma firma, String nachname, String vorname, String email, String passwort, boolean admin, boolean newsletter, boolean enabled) {
       this.firma = firma;
       this.nachname = nachname;
       this.vorname = vorname;
       this.email = email;
       this.passwort = passwort;
       this.admin = admin;
       this.newsletter = newsletter;
       this.enabled = enabled;
    }
   
    public Integer getIdBenutzer() {
        return this.idBenutzer;
    }
    
    public void setIdBenutzer(Integer idBenutzer) {
        this.idBenutzer = idBenutzer;
    }
    public Firma getFirma() {
        return this.firma;
    }
    
    public void setFirma(Firma firma) {
        this.firma = firma;
    }
    public String getNachname() {
        return this.nachname;
    }
    
    public void setNachname(String nachname) {
        this.nachname = nachname;
    }
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPasswort() {
        return this.passwort;
    }
    
    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public boolean isNewsletter() {
        return this.newsletter;
    }
    
    public void setNewsletter(boolean newsletter) {
        this.newsletter = newsletter;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }




}


