package ch.kbw.portalumni.hibernatedata;
// Generated Apr 29, 2018 1:00:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Firma generated by hbm2java
 */
public class Firma  implements java.io.Serializable {


     private Integer idFirma;
     private String name;
     private String adresse;
     private String ort;
     private Set<Benutzer> benutzers = new HashSet<Benutzer>(0);

    public Firma() {
    }

	
    public Firma(String name) {
        this.name = name;
    }
    public Firma(String name, String adresse, String ort, Set<Benutzer> benutzers) {
       this.name = name;
       this.adresse = adresse;
       this.ort = ort;
       this.benutzers = benutzers;
    }
   
    public Integer getIdFirma() {
        return this.idFirma;
    }
    
    public void setIdFirma(Integer idFirma) {
        this.idFirma = idFirma;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getOrt() {
        return this.ort;
    }
    
    public void setOrt(String ort) {
        this.ort = ort;
    }
    public Set<Benutzer> getBenutzers() {
        return this.benutzers;
    }
    
    public void setBenutzers(Set<Benutzer> benutzers) {
        this.benutzers = benutzers;
    }




}


