package ch.kbw.portalumni.hibernatedata;
// Generated Apr 29, 2018 1:00:13 PM by Hibernate Tools 4.3.1



/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private int idNews;
     private String text;
     private String titel;
     private String img1;
     private String img2;
     private String img3;

    public News() {
    }

    public News(int idNews, String text, String titel, String img1, String img2, String img3) {
       this.idNews = idNews;
       this.text = text;
       this.titel = titel;
       this.img1 = img1;
       this.img2 = img2;
       this.img3 = img3;
    }
   
    public int getIdNews() {
        return this.idNews;
    }
    
    public void setIdNews(int idNews) {
        this.idNews = idNews;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getTitel() {
        return this.titel;
    }
    
    public void setTitel(String titel) {
        this.titel = titel;
    }
    public String getImg1() {
        return this.img1;
    }
    
    public void setImg1(String img1) {
        this.img1 = img1;
    }
    public String getImg2() {
        return this.img2;
    }
    
    public void setImg2(String img2) {
        this.img2 = img2;
    }
    public String getImg3() {
        return this.img3;
    }
    
    public void setImg3(String img3) {
        this.img3 = img3;
    }




}


